
import reduceArray from './reduceToObject';

export default reduceArray([
    'GET_COMPETITIONS_LIST_SUCCESS',
    'GET_COMPETITIONS_LIST_REQUEST',
    'GET_COMPETITIONS_LIST_ERROR',
    'GET_ACTIVE_COMPETITION_SUCCESS',
    'GET_ACTIVE_COMPETITION_ERROR',
    'GET_ACTIVE_COMPETITION_REQUEST'
]);
