version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: competitions
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=pgsql
      - ADMINER_DEFAULT_DB_NAME=competitions
